name: Deploy to PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Start
        run: |
          ls -la
          git status
          pwd
