name: Deploy to PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v2.0
      #   with:
      #     envkey_DEBUG: false
      #     envkey_SOME_API_KEY: "123456abcdef"
      #     envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     envkey_VARIABLE: ${{ vars.SOME_ACTION_VARIABLE }}
      #     some_other_variable: foobar
      #     directory: <directory_name>
      #     file_name: .env
      #     fail_on_empty: false
      - name: Start
        run: |
          ls -la
          git status
          cp env.prod .env
          npm run prod
